#!/usr/bin/env python3
"""context_pack.py — regenerate CONTEXT-PACK.md (BUILD-SPEC §2.2, §7.1).

The Context Pack is the compressed orientation a fresh session reads after
STATE.json and HANDOFF.md. It is *generated*, never hand-edited: a hand-edited
orientation document drifts, and a drifted map is worse than none.

    context_pack.py            write CONTEXT-PACK.md from current state
    context_pack.py --stdout   print instead of writing
"""

from __future__ import annotations

import argparse
import sys
from datetime import timedelta
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))

from lib import clock, events, killswitch, paths, receipts, state  # noqa: E402
from lib.atomic import write_text_atomic  # noqa: E402

SLICES = {
    "VS-1": "Spine — repo, hooks, state plane, receipt chain, core CI",
    "VS-2": "Simulation Harness — sim/, virtual clock, fakes, chaos",
    "VS-3": "A2A over T1/T2 — envelope, dispatcher, registry, minimal policy",
    "VS-4": "Continuity + Kill Switch — succession, reaper, dead-man, escrow",
    "VS-5": "Tier 0 Agents — 7 agent cards, budget, heartbeat, two-key",
    "VS-6": "Control Room — Moxt Workflow mirror + approval path",
    "VS-7": "Config Pipeline — statistical canary, probe fleet, auto-rollback",
    "VS-8": "Growth Spine — event taxonomy, schemas, funnel, first journey",
    "VS-9": "Experiment Loop — guardrails, SRM, readouts",
    "VS-10": "Revenue Command Center — dashboards, unit economics",
    "VS-11": "Autonomy Ratchet + Shadow Mode",
    "VS-12": "(optional) HTTP Gateway — latency cache only",
}


def build() -> str:
    try:
        s = state.read()
        snapshot = state.summarize(s)
    except state.StateError as exc:
        s = None
        snapshot = f"(STATE.json unavailable: {exc})"

    ks = killswitch.read_state()
    rstats = receipts.stats()

    end = clock.now().date()
    recent = list(events.iter_range(end - timedelta(days=1), end, world="prod"))[-12:]
    event_lines = "\n".join(
        f"  - `{e.get('ts', '?')[:19]}` {e.get('type')} "
        f"by {e.get('actor', {}).get('id', '?')}"
        for e in recent
    ) or "  (no events in the last 24h)"

    heads = []
    chain_dir = paths.repo_root() / "receipts" / "_chain"
    if chain_dir.exists():
        from lib.atomic import read_json
        for f in sorted(chain_dir.glob("*.head.json")):
            h = read_json(f, default={}) or {}
            heads.append(f"  - {f.name[:-10]}: {h.get('count', 0)} receipts, "
                         f"head `{str(h.get('hash'))[:18]}…`")
    head_lines = "\n".join(heads) or "  (no receipts yet)"

    slice_now = (s or {}).get("active_slice", "VS-1")

    return f"""# CONTEXT-PACK — compressed session state

> Generated by `scripts/context_pack.py` at {clock.iso()}. Do not hand-edit;
> regenerate. New session / new account: read ONBOARDING.md first (cold-start protocol).
> Read order for a new session: ONBOARDING.md → STATE.json → HANDOFF.md → this file.

## Snapshot

```
{snapshot}
```

## Safety

- Kill switch: **{ks.verdict.value}** ({ks.detail})
- Receipt chain: {rstats['total']} receipts · crash_rate {rstats['crash_rate']:.2%} (budget 2%)
- Active slice: **{slice_now}** — {SLICES.get(slice_now, '?')}

## Receipt chains

{head_lines}

## Last events (24h, prod)

{event_lines}

## The session protocol (BUILD-SPEC §0)

1. SYNC — `scripts/fsp.py status` + HANDOFF.md + recent receipts + kill switch
2. GAP SCAN — distance to the current slice's Definition of Done (§17)
3. CLAIM — `scripts/fsp.py claim <workstream> --agent <id>` (TTL 90m)
4. PLAN — at most 7 steps, each with a named artifact
5. SIM — run the related sim/ scenario first; red means no production
6. EXECUTE — real code, never placeholders
7. VERIFY — run tests, report real output
8. EMIT — event + receipt (with prev_receipt_hash) + atomic commit
9. HANDOFF — rewrite HANDOFF.md, release the lease

## Iron rules

1. No config reaches users without QA.  2. No campaign without hypothesis and
stop condition.  3. No session ends without a HANDOFF.  4. No secret enters
the repo.  5. No decision without owner, evidence and rollback.
6. "I don't know" equals "stop" — an unreadable safety control is engaged,
not clear.
"""


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(prog="context_pack.py")
    parser.add_argument("--stdout", action="store_true")
    args = parser.parse_args(argv)
    text = build()
    if args.stdout:
        print(text)
    else:
        write_text_atomic(paths.context_pack_file(), text)
        print(f"wrote {paths.rel(paths.context_pack_file())} ({len(text)} bytes)")
    return 0


if __name__ == "__main__":
    try:
        raise SystemExit(main())
    except Exception as exc:
        print(f"context_pack: {type(exc).__name__}: {exc}", file=sys.stderr)
        raise SystemExit(2)
